version: "3"
services:
  statamic:
    container_name: statamic
    build: .
    image: mystatamic:latest
    restart: unless-stopped
    env_file: .env

    volumes:
      - statamic-users:/app/users
      - statamic-content:/app/content
      - statamic-assets:/app/public/assets

    ports:
      - "80"
      - "443"


  backup:
    image: offen/docker-volume-backup:v2
    env_file: .env
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./backups:/etc/dockervolumebackup/conf.d
        - statamic-content:/backup/statamic-content-backup:ro
        - statamic-assets:/backup/statamic-assets-backup:ro

volumes:
    statamic-users:
    statamic-content:
    statamic-assets: