version: "3"
services:
  statamic:
    container_name: statamic
    build: .
    image: mystatamic:latest
    restart: unless-stopped
    env_file: stack.env
    # environment:

    volumes:
      - statamic-users:/app/users
      - statamic-content:/app/content
      - statamic-assets:/app/public/assets

    ports:
      - "80"
      - "443"

volumes:
    statamic-users:
    statamic-content:
    statamic-assets: